install:
- pip install unittest2
- pip install .
language: python
python:
- '2.7'
script:
- docker pull milansuk/python-black
- docker run milansuk/python-black:latest black --check .
- echo "No tests are there"
