before_install:
- pip3 install black
- sudo apt-get -y install python3-pip && sudo apt-get update
install:
- pip install unittest2
language: python
python:
- '2.7'
- '3.6'
script:
- black --check .
- echo "No tests"
