before_install:
- sudo apt-get -y install python3-pip && sudo apt-get update
- pip3 install black
install:
- pip install unittest2
language: python
python:
- '2.7'
script:
- black --check .
- echo "No tests"
