install:
- pip install unittest2
language: python
matrix:
  include:
    - name: "python2"
      python: 2.7
      env:
        - TEST_CMD = "echo 'no test'"
    - name: "python3"
      python: 3.6
      env:
        - TEST_CMD = "pip3 install -y black && black --check ."
script:
- $TEST_CMD
- echo "No tests"
