before_install:
- sudo apt-get -y install python3-pip python-dev
- sudo python3 -m pip3 install black
install:
- pip install unittest2
language: python
python:
- '2.7'
script:
- black --check .
- echo "No tests"
