install:
- pip install unittest2
language: python
matrix:
  include:
    - name: "python2"
      python: 2.7
      env:
        - TEST_CMD = "echo 'no test'"
    - name: "python3"
      python: 3.6
      env:
        - TEST_CMD="pip3 install black"
        - TEST_SECOND_CMD="black --check ."
script:
- $TEST_CMD
- $TEST_SECOND_CMD
- echo "No tests"
