install:
- pip install unittest2
- pip install .
matrix:
  include:
    - name: "python2.7"
      python: 2.7
    - env:
      - INSTALL_BLACK_CMD="pip3 install black"
      - TEST_BLACK_CMD="black --check ."
      name: python3.6
      python: 3.6
script:
- $INSTALL_BLACK_CMD
- $TEST_BLACK_CMD
- echo "No tests are there"
